### ISSUE TITLE
pair_predict的r值和f1值几乎是0

### ISSUE THREAD

**Issue by licm062** [bigorange-Petrichor/IE-CNN#1]
请问，我跑这个代码过程中显示pair_predict的r值和f1值几乎是0，是为什么呀

**Comment by zifengcheng** [comment]
是所有折都为0吗？还是某一折？
可能有些设置跟原作者的不太一致，具体你可以参考下原作者的tensorflow实现。

**Comment by licm062** [comment]
是所有的fold，看emotion和cause结果还挺正常的，pair_predict的p值也是正常的

**Comment by zifengcheng** [comment]
我这边在第一折跑了一下，结果是正常的。torch版本是1.8.0。
超参我看了下只有词嵌入层的dropout是不一致的，我改成了0.2.
如果放词嵌入放进去初始化的话，结果应该是正常的。你可以再试一下。

**Comment by licm062** [comment]
我用了pytorch1.6.0，也放了词嵌入，只有r和f1两个值有问题，实在找不到是哪里出了问题，可以麻烦您帮忙看一下下吗，我的微信18716038196，谢谢您啦

**Comment by zifengcheng** [comment]
不好意思，因为我最近要忙期末考试等，时间比较紧，你可以复现下原作者的代码https://github.com/mark-xhchen/IE-CNN.
