### ISSUE TITLE
Is there any cheating tricks for test set performance evaluation in function 'mapcausepos'?

### ISSUE THREAD

**Issue by qwertyuiopasdfghjklzxcn** [bigorange-Petrichor/IE-CNN#2]
`            for cause in true_cause:
                for emo in true_emo:
                    if cause[1] == emo[1]:
                        true_pair.append([cause[0], emo[0]])`
at line 311~314 in prepare_data.py.
This code segment regards any true emotion clause and true cause clause with the same emotion type, as the ground truth emotion-cause pairs. However, the emotion clause and cause clause with _the same emotion type_ doesn't indicate that they are _emotion-cause pairs_. 
For example, in document 14, this code gives the _ground truth_ emotion-cause pair set {(2,1),(6,1),(2,6),(6,6)}, while the dataset itself gives the ground truth emotion-cause pair set {(2,1), (6,6)}. 
In a word, you are evaluating your test set performance on a broader ground truth emotion cause pair set. I would appreciate it if you could give some description.

**Comment by zifengcheng** [comment]
Hi, the code we refer to the authors' code (https://github.com/mark-xhchen/IE-CNN). 
I'm not sure if they wrote it wrong, you can ask the original author.

**Comment by qwertyuiopasdfghjklzxcn** [comment]
Thanks. I think that they wrote it wrong. I will move this issue to the original author's repository.
